# Julia tutorial

https://github.com/NTUMitoLab/BEBI-5009

**Reference**
1. [Think Julia](https://benlauwens.github.io/ThinkJulia.jl/latest/book.html)
2. [From zero to Julia](https://techytok.com/from-zero-to-julia/)
3. [Julia cheat sheet](https://juliadocs.github.io/Julia-Cheat-Sheet/) if you are familiar with Python and/or MATLAB.
4. [Official Julia Docs](https://docs.julialang.org/) for dictionary look-up.
5. [Julia for Pythonistas](https://colab.research.google.com/github/ageron/julia_notebooks/blob/master/Julia_for_Pythonistas.ipynb)

# Why Julia?

- Python-like syntax
- C-like speed (after you run for the 1st time)
- Flexibility across packages
- Most importantly, comprehensive toolbox for this course

# Install and run Julia

1. [Download Julia](https://julialang.org/downloads/). You could give version `1.6-rc1` a try because it loads much fater than previous versions.
2. Open the Julia terminal and enter the following commands to install IJulia, the Julia kernel for Jupyter notebooks.

```julia
using Pkg

pkg"add IJulia"
```

3. Run Jupyter Lab

```julia
using IJulia

IJulia.jupyterlab()  # Will open at ${HOME}, that is "C:\Users\yourname\" in Windows.
```

PS. Another recommendation is [VS Code](https://code.visualstudio.com/) with [Julia extension](https://www.julia-vscode.org/), more suitable for structured code.

# First steps

## How to see the results

`@show`,`println()`, `display()`, inline display for the last expression

In [1]:
# Comments: Screen output

#=
I'm multiline comments
To demonstrate different types of outputs 
for different needs
=#

# Regular text output: println() and print()
println("Using println")
println(1, 2, 3)

# @show will print something like x = val
@show "Using show"
@show 1+1, 2-2, 3*3

# display() for interactive use
# the message will go to the top of the output cell
display("Use display")

# Inline display of the last expression
"Done"

"Use display"

Using println
123
"Using show" = "Using show"
(1 + 1, 2 - 2, 3 * 3) = (2, 0, 9)


"Done"

## Assigning variables for later use

Binding a name to a value : `x = val`.

`val` could be a literal (numbers, string, symbols), a data structure, a type itself, a function, a module, etc. 

In [2]:
x = 1
y = 2
z = x + y

@show x, y
@show z

# Constant variable, better optimized
# and will give a warning (event an error) 
# if someone attempted to modify it
const pi = 3.14

(x, y) = (1, 2)
z = 3


3.14

## Special characters

Type `\xxx <space>` 

e.g. `\pi <space>` => `π`

In [3]:
π

π = 3.1415926535897...

## Binary operators

In [4]:
# Binary operators
a = 2
b = 3

# Addition
@show a + b

# Substraction
@show a - b

# Multiplication
@show a * b

# Floating point Division
@show b / a
@show typeof(b / a)

# Power
@show a^a

# Modulus
@show b % a
@show typeof(a÷b)

# integer division: \div <space>`, equivalent to div(a, b)`
@show a÷b

# rational number
@show a//b      

# Approximation `\approx` for floats, equivalent to isapprox(a, b)`
@show 1e10 + 1.0 ≈ 1e10

# Convert to another type: `convert(T, x)` 
@show convert(Float64, a)

a + b = 5
a - b = -1
a * b = 6
b / a = 1.5
typeof(b / a) = Float64
a ^ a = 4
b % a = 1
typeof(a ÷ b) = Int64
a ÷ b = 0
a // b = 2//3
1.0e10 + 1.0 ≈ 1.0e10 = true
convert(Float64, a) = 2.0


2.0

## Frequently-used functions

In [5]:
# Some math functions

@show sin(0.5*π)
@show cos(0.5*π)
@show sqrt(π)
@show log(10)
@show log10(10)
@show exp(-5)
@show exp(1e-10)-1, expm1(1e-10)
@show rand()
@show rand(1:6)
@show rand("Hello");

sin(0.5π) = 1.0
cos(0.5π) = 6.123233995736766e-17
sqrt(π) = 1.7724538509055159
log(10) = 2.302585092994046
log10(10) = 1.0
exp(-5) = 0.006737946999085467
(exp(1.0e-10) - 1, expm1(1.0e-10)) = (1.000000082740371e-10, 1.00000000005e-10)
rand() = 0.055627562473313796
rand(1:6) = 6
rand("Hello") = 'l'


In [6]:
?rand

search: rand randn transcode macroexpand @macroexpand @macroexpand1



```
rand([rng=GLOBAL_RNG], [S], [dims...])
```

Pick a random element or array of random elements from the set of values specified by `S`; `S` can be

  * an indexable collection (for example `1:9` or `('x', "y", :z)`),
  * an `AbstractDict` or `AbstractSet` object,
  * a string (considered as a collection of characters), or
  * a type: the set of values to pick from is then equivalent to `typemin(S):typemax(S)` for integers (this is not applicable to [`BigInt`](@ref)), to $[0, 1)$ for floating point numbers and to $[0, 1)+i[0, 1)$ for complex floating point numbers;

`S` defaults to [`Float64`](@ref). When only one argument is passed besides the optional `rng` and is a `Tuple`, it is interpreted as a collection of values (`S`) and not as `dims`.

!!! compat "Julia 1.1"
    Support for `S` as a tuple requires at least Julia 1.1.


# Examples

```julia-repl
julia> rand(Int, 2)
2-element Array{Int64,1}:
 1339893410598768192
 1575814717733606317

julia> using Random

julia> rand(MersenneTwister(0), Dict(1=>2, 3=>4))
1=>2

julia> rand((2, 3))
3

julia> rand(Float64, (2, 3))
2×3 Array{Float64,2}:
 0.999717  0.0143835  0.540787
 0.696556  0.783855   0.938235
```

!!! note
    The complexity of `rand(rng, s::Union{AbstractDict,AbstractSet})` is linear in the length of `s`, unless an optimized method with constant complexity is available, which is the case for `Dict`, `Set` and `BitSet`. For more than a few calls, use `rand(rng, collect(s))` instead, or either `rand(rng, Dict(s))` or `rand(rng, Set(s))` as appropriate.



## String manipulation 

See: https://benlauwens.github.io/ThinkJulia.jl/latest/book.html#chap08

A `string` is a sequence of characters.

* `''` for one character
* `" ... "` for one line strings
* `""" ....  """` for multiline strings
* `str1*str2` or `string(str1, str2)` to concatenate strings (the latter is recommended for it's more general and works not only in strings but also anything can turn into strings (e.g. numbers))
* `^` to repeat a string: `str^3`
* `[i]` to access individual character
* `$` to insert values into a string
* `string(a, b)` to convert a and b into strings and concatenate them

In [7]:
@show 'a' == "a"

@info """ 
Multiline
string
is here
"""

'a' == "a" = false


┌ Info:  
│ Multiline
│ string
│ is here
└ @ Main In[7]:3


In [8]:
str1 = "BEBI"

str2 = "5009"

string("The class is ", str1, '-', str2)

"The class is BEBI-5009"

In [9]:
"The class is $str1-$str2"

"The class is BEBI-5009"

In [10]:
println("The class is ", str1, '-', str2)

The class is BEBI-5009


In [11]:
str1[2]

'E': ASCII/Unicode U+0045 (category Lu: Letter, uppercase)

In [12]:
str1^3

"BEBIBEBIBEBI"

In [13]:
str1*str2

"BEBI5009"

# Controlling the flow of execution

## `if` clause

```julia
if cond1
    exe1
elseif cond2
    exe2
else
    exe3
end
```

In [14]:
score = 30 + 70 * rand()

println("scroe is ", score)

if 80 < score <= 100
  println("Good")
elseif 60 < score <= 80
  println("Okay")
else
  println("Uh-Oh")
end

scroe is 65.07482448776685
Okay


## Iterations (Loops)

**while** loops

```julia
while cond
    # code here
end
```

**for** loops

```julia
for x in sequence
    # process x
end
```

* Use `break` to exit the loop
* Use `continue` to jump to the next `x` or `cond`
* Use `start[:step]:end` for ranges (end-inclusive)

In [15]:
s = 0

for i in 1:100
  s = s + i
end

println("Sum of 1 to 100 is ", s)

Sum of 1 to 100 is 5050


In [16]:
n = rand(1:1000000)
print("The length of hailstone sequence for ", n, " is ")

step = 0

# Hailstone sequence (3n+1 problem)
while n != 1
  if n % 2 == 0
    n = n÷2
  else
    n = 3n+1
  end
  step = step + 1
end

println(step)

The length of hailstone sequence for 217503 is 155


# Functions

For code reuse and encapsulating algorithms.

* Formal definition. `x` can be 0 - multiple arguments.

```julia
function f(x)
    ....
end
```

* one-liner functions

```julia
f(x) = ....
```

* anonymous functions

```julia
x -> ....
```

In [17]:
"Mechaelis-Menton function"  # Function documentations
function mm(x, k)
  result = x / (x +k)
  return result              # With explicit return statement
end

"Repressive Mechaelis-Menton function"
function mmr(x, k)
  mm(k, x)                   # Implicitly returns the last statement, not recommended
end

"Hill function"
hill(x, k, n) = mm(x^n, k^n)  # simple function are best for one-liners

"Repressive hill function"
hillr = (x, k, n) -> hill(k, x, n)  # Usually for single use (e.g. inside map()) only

hillr

In [18]:
# Example for anonymous functions
# map(f, seq) takes a function and a sequence

map(x -> x^2, 1:5)

5-element Array{Int64,1}:
  1
  4
  9
 16
 25

**Optional arguments**

https://techytok.com/lesson-functions/#optional-positional-arguments

```julia
function func(a, b, c=1)
...
end
```

**Keyword arguments**

https://techytok.com/lesson-functions/#keyword-arguments

```julia
function func(a, b; c=1)
    ...
end
```

# Sequencial objects and Data Structures

https://techytok.com/lesson-data-structures/

* **1**-based indexing
* `length(seq)` to get the size of seq
* `[]` to access elements in sequences (arrays, dictionaries, tuples)
    * `[start:step:end]` to access a slie of a sequences (not for dictionaries)
* Empty arrays and dictionaries may have element type of `Any` and thus slower speed.
* Use `...` to splatting (unpack) arrays / tuples and pass its arguments to a function
* Objects may share memory space, beware changing values accidentally
* Dot syntax (e.g. `a .+ b`) for element-wise (broadcasting) operations

## Ranges

Low-cost alternative to full arrays if the sequence is evenly spaced.

In [19]:
# Julia's linspace()
range(1, 10, length=100)

1.0:0.09090909090909091:10.0

In [20]:
r1 = 1:2:9  # Lazy evaluation to save mem/CPU

1:2:9

In [21]:
@show length(r1)

length(r1) = 5


5

In [22]:
collect(r1)  # Until it's really needed (e.g. converting to arrays)

5-element Array{Int64,1}:
 1
 3
 5
 7
 9

In [23]:
# Julia's logspace
# Using dot syntax for element-wise (broadcasting) operations 
exp10.(-3.0:3.0)

7-element Array{Float64,1}:
    0.001
    0.01
    0.1
    1.0
   10.0
  100.0
 1000.0

## Arrays

The bread and butter for scientific computing. Similar to `numpy`'s `ndarrays`.

But with some caveats:
* 1-based indexing
* Column-major (like Fortran) instead of C-style row-major

In [24]:
# 1D array (column vector)
x = [5, 6, 7]

3-element Array{Int64,1}:
 5
 6
 7

In [25]:
# 2D array (matrix)
A = [1 2 3;
     4 5 6]  

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [26]:
# Matrix-vector multiplication
@show A*x

A * x = [38, 92]


2-element Array{Int64,1}:
 38
 92

In [27]:
# Find the solution of x of Ax = b
# Using left division operator `/`
b = [38, 92]
@show A\b  # Should be approximately [5, 6, 7]

A \ b = [5.000000000000002, 6.0, 6.999999999999997]


3-element Array{Float64,1}:
 5.000000000000002
 6.0
 6.999999999999997

In [28]:
# convert `arr` to an 1D array (i.e. vectors)

@show vec(A)

vec(A) = [1, 4, 2, 5, 3, 6]


6-element Array{Int64,1}:
 1
 4
 2
 5
 3
 6

In [29]:
# Arrays are mutable (i.e. you can replace the contents)

b = copy(x)  # Make a copy to preserve the original

3-element Array{Int64,1}:
 5
 6
 7

In [30]:
b[1] = 0
@show b

b = [0, 6, 7]


3-element Array{Int64,1}:
 0
 6
 7

In [31]:
# append `x` at the end of `arr`
append!(b, 10)

4-element Array{Int64,1}:
  0
  6
  7
 10

## Tuples

* Immutable (you could not replace the elements)
* Stack-allocated, faster than arrays in short sequences

In [32]:
a = (1, 2, 3)

@show a[1]

a[1] = 1


1

In [33]:
a[1] = 0  # (you could not replace the elements)

LoadError: MethodError: no method matching setindex!(::Tuple{Int64,Int64,Int64}, ::Int64, ::Int64)

In [34]:
tuple(1, 2, 3)

(1, 2, 3)

In [35]:
# Splat operator ... to unfold a sequence to a series of arguments
# Slow at long sequence
tuple([1, 2, 3]...)

(1, 2, 3)

In [36]:
# Returns multiple values in a function
function return_multiple()
    return (4, 5, 6)
end

return_multiple()

(4, 5, 6)

## Namedtuples

Tuples with named fields so you dont't have to remember the index number.

In [37]:
nt = (a=1, b=2, c=4)

(a = 1, b = 2, c = 4)

In [38]:
nt.a == nt[:a] && nt.a == nt[1]

true

## Comprehensions

In [39]:
# comprehension for shorhand of sequence / matrix construction
[i + j for i in 0:3, j in 0:3]  # Constructing a 2D array

4×4 Array{Int64,2}:
 0  1  2  3
 1  2  3  4
 2  3  4  5
 3  4  5  6

In [40]:
[i + j for i in 0:3 for j in 0:3] # Note the difference (a 1D array)

16-element Array{Int64,1}:
 0
 1
 2
 3
 1
 2
 3
 4
 2
 3
 4
 5
 3
 4
 5
 6

## Dictionaries

Mapping of `key` => `value`.

In [41]:
eng2sp = Dict("one" => "uno", "two" => "dos", "three" => "tres")

Dict{String,String} with 3 entries:
  "two"   => "dos"
  "one"   => "uno"
  "three" => "tres"

In [42]:
@show keys(eng2sp)

keys(eng2sp) = ["two", "one", "three"]


Base.KeySet for a Dict{String,String} with 3 entries. Keys:
  "two"
  "one"
  "three"

In [43]:
@show values(eng2sp)

values(eng2sp) = ["dos", "uno", "tres"]


Base.ValueIterator for a Dict{String,String} with 3 entries. Values:
  "dos"
  "uno"
  "tres"

In [44]:
@show eng2sp["one"]

eng2sp["one"] = "uno"


"uno"

In [45]:
@show get(eng2sp, "one", "N/A")

get(eng2sp, "one", "N/A") = "uno"


"uno"

In [46]:
@show eng2sp["four"]

LoadError: KeyError: key "four" not found

In [47]:
@show get(eng2sp, "four", "N/A")

get(eng2sp, "four", "N/A") = "N/A"


"N/A"

In [48]:
# Add entry
eng2sp["four"] = "cuatro"

@show eng2sp["four"]

eng2sp["four"] = "cuatro"


"cuatro"

In [49]:
# Unordered keys
for (k ,v) in eng2sp
    println(k, " => ", v)
end

two => dos
four => cuatro
one => uno
three => tres


In [50]:
# Alternative ways to build a dict
# From a tuple
t = [('a', 1), ('c', 3), ('b', 2)]
@show Dict(t)

Dict(t) = Dict('a' => 1,'c' => 3,'b' => 2)


Dict{Char,Int64} with 3 entries:
  'a' => 1
  'c' => 3
  'b' => 2

In [51]:
d = Dict(zip("abc", 1:3))

Dict{Char,Int64} with 3 entries:
  'a' => 1
  'c' => 3
  'b' => 2

## Custom data structures

`struct` or `mutable struct`

I recommend use `struct` with a helper: [Parameters.jl](https://github.com/mauro3/Parameters.jl)

```julia
using Pkg
Pkg.add("Parameters")
```

In [52]:
using Parameters

# The famous point example
@with_kw struct Point
    x = 0.0
    y = 0.0
end

Point

In [53]:
origin = Point()  # Use default values

Point
  x: Float64 0.0
  y: Float64 0.0


In [54]:
pA = Point(1, 2)

Point
  x: Int64 1
  y: Int64 2


In [55]:
# Define a function specialized to Point type
distance(a::Point) = hypot(a.x, a.y)
distance(a::Point, b::Point) = hypot(a.x - b.x, a.y - b.y)

distance (generic function with 2 methods)

In [56]:
distance(pA) ≈ sqrt(5)

true

In [57]:
pB = Point(pA; y=4)  # Reuse some of a's value
distance(pA, pB)

2.0